build:
	cd netServer
	$(MAKE) build
	cd ..
        cd omniOrbClient
        $(MAKE) build
        cd ..

clean:
	cd netServer
	$(MAKE) clean
	cd ..
        cd omniOrbClient
        $(MAKE) clean
        cd ..
