include ..\..\..\..\MakeVars

build:
	cd RTESSupplier
	$(MAKE)
	cd ..
	cd RTESIIOPNetConsumer
	$(MAKE)
	cd ..

clean:
	cd RTESSupplier
	$(MAKE) clean
	cd ..
	cd RTESIIOPNetConsumer
	$(MAKE) clean
	cd ..
	