include ..\..\..\..\MakeVars

build:
	cd net
	$(MAKE) build
	cd ..
        cd java
        $(MAKE) build
        cd ..

clean:
	cd net
	$(MAKE) clean
	cd ..
        cd java
        $(MAKE) clean
        cd ..

start-server:
	cd net
	$(MAKE) start-server
	cd ..

stop-server:
	cd net
	$(MAKE) stop-server
	cd ..
