enum TestEnumForU2 {
    A1, B1, C1
};


union TestUnionE2 switch(TestEnumForU2) {
    case A1: short valE0;
    case B1:
    case C1: long valE1;
    // omniorb does use indirection to serialise typecode, if the following is used: TestEnumForU2 valE1;
    // this is not supported by IIOP.NET at the moment
};
