/* Generated By:JJTree: Do not edit this line. ASTattr_dcl.java */

package parser;

public class ASTattr_dcl extends SimpleNode {
  public ASTattr_dcl(int id) {
    super(id);
  }

  public ASTattr_dcl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  private boolean m_readOnly = false;
  public boolean isReadOnly() {
    return m_readOnly;
  }
  public void setReadOnly(boolean readOnly) {
      m_readOnly = readOnly;
  }
}
