/* Generated By:JJTree: Do not edit this line. ASTand_expr.java */

package parser;

public class ASTand_expr extends SimpleNode {
  public ASTand_expr(int id) {
    super(id);
  }

  public ASTand_expr(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
