/* Generated By:JJTree: Do not edit this line. ASTarray_declarator.java */

package parser;

public class ASTarray_declarator extends SimpleNodeWithIdent {
  public ASTarray_declarator(int id) {
    super(id);
  }

  public ASTarray_declarator(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
