/* Generated By:JJTree: Do not edit this line. ASTboolean_type.cs */

using System;

namespace parser {

public class ASTboolean_type : SimpleNode {
  public ASTboolean_type(int id) : base(id) {
  }

  public ASTboolean_type(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "boolean";
  }
  
}


}

