/* Generated By:JJTree: Do not edit this line. ASTbase_type_spec.cs */

using System;

namespace parser {

public class ASTbase_type_spec : SimpleNode {
  public ASTbase_type_spec(int id) : base(id) {
  }

  public ASTbase_type_spec(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return ((SimpleNode)jjtGetChild(0)).GetIdentification();
  }  
  
}


}

