/* Generated By:JJTree: Do not edit this line. ASTcontext_expr.java */

/* ASTcontext_expr.java
 * 
 * Project: IIOP.NET
 * IDLToCLSCompiler
 * 
 * WHEN      RESPONSIBLE
 * 14.02.03  Dominic Ullmann (DUL), dul@elca.ch
 *  
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */


package parser;

import java.util.LinkedList;

public class ASTcontext_expr extends SimpleNode {

    #region IFields

    private LinkedList m_contextElements = new LinkedList();

    #endregion IFields
    #region IConstructors

    public ASTcontext_expr(int id) {
        super(id);
    }

    public ASTcontext_expr(IDLParser p, int id) {
        super(p, id);
    }
    
    #endregion IConstructors
    #region IMethods

    /** Accept the visitor. **/
    public Object jjtAccept(IDLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
  
    public LinkedList getContextElements() {
        return m_contextElements;
    }
    
    public void addContextElement(String contextElement) {
        m_contextElements.add(contextElement);    
    }
    
    #endregion IMethods
    
}
