/* Generated By:JJTree: Do not edit this line. ASTchar_type.cs */

using System;

namespace parser {

public class ASTchar_type : SimpleNode {
  public ASTchar_type(int id) : base(id) {
  }

  public ASTchar_type(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "char";
  }

}


}

