/* Generated By:JJTree: Do not edit this line. ASTcontext_expr.java */

package parser;

import java.util.LinkedList;

public class ASTcontext_expr extends SimpleNode {
  public ASTcontext_expr(int id) {
    super(id);
  }

  public ASTcontext_expr(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  private LinkedList m_contextElements = new LinkedList();
  public LinkedList getContextElements() {
      return m_contextElements;
  }
  public void addContextElement(String contextElement) {
      m_contextElements.add(contextElement);    
  }
}
