/* Generated By:JJTree: Do not edit this line. ASTcase_label.java */

package parser;

public class ASTcase_label extends SimpleNode {
  public ASTcase_label(int id) {
    super(id);
  }

  public ASTcase_label(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
