/* Generated By:JJTree: Do not edit this line. ASTcasex.cs */

using System;

namespace parser {

public class ASTcasex : SimpleNode {
  public ASTcasex(int id) : base(id) {
  }

  public ASTcasex(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "case in " + ((SimpleNode)jjtGetParent()).GetEmbedderDesc();
  }
}


}

