/* Generated By:JJTree: Do not edit this line. ASTconst_exp.java */

package parser;

public class ASTconst_exp extends SimpleNode {
  public ASTconst_exp(int id) {
    super(id);
  }

  public ASTconst_exp(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
