/* Generated By:JJTree: Do not edit this line. ASTcomplex_declarator.cs */

using System;

namespace parser {

public class ASTcomplex_declarator : SimpleNode {
  public ASTcomplex_declarator(int id) : base(id) {
  }

  public ASTcomplex_declarator(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

