/* Generated By:JJTree: Do not edit this line. ASTcomplex_declarator.java */

package parser;

public class ASTcomplex_declarator extends SimpleNode {
  public ASTcomplex_declarator(int id) {
    super(id);
  }

  public ASTcomplex_declarator(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
