/* Generated By:JJTree: Do not edit this line. ASTconstr_type_spec.cs */

using System;

namespace parser {

public class ASTconstr_type_spec : SimpleNode {
  public ASTconstr_type_spec(int id) : base(id) {
  }

  public ASTconstr_type_spec(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

