/* Generated By:JJTree: Do not edit this line. ASTdefinition.java */

package parser;

public class ASTdefinition extends SimpleNode {
  public ASTdefinition(int id) {
    super(id);
  }

  public ASTdefinition(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
