/* Generated By:JJTree: Do not edit this line. ASTdeclarators.java */

package parser;

public class ASTdeclarators extends SimpleNode {
  public ASTdeclarators(int id) {
    super(id);
  }

  public ASTdeclarators(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
