/* Generated By:JJTree: Do not edit this line. ASTdeclarators.cs */

using System;

namespace parser {

public class ASTdeclarators : SimpleNode {
  public ASTdeclarators(int id) : base(id) {
  }

  public ASTdeclarators(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

