/* Generated By:JJTree: Do not edit this line. ASTexcept_dcl.java */

package parser;

public class ASTexcept_dcl extends SimpleNodeWithIdent {
  public ASTexcept_dcl(int id) {
    super(id);
  }

  public ASTexcept_dcl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
