/* Generated By:JJTree: Do not edit this line. ASTelement_spec.java */

package parser;

public class ASTelement_spec extends SimpleNode {
  public ASTelement_spec(int id) {
    super(id);
  }

  public ASTelement_spec(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
