/* Generated By:JJTree: Do not edit this line. ASTexport.java */

package parser;

public class ASTexport extends SimpleNode {
  public ASTexport(int id) {
    super(id);
  }

  public ASTexport(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
