/* Generated By:JJTree: Do not edit this line. ASTfixed_array_size.java */

package parser;

public class ASTfixed_array_size extends SimpleNode {
  public ASTfixed_array_size(int id) {
    super(id);
  }

  public ASTfixed_array_size(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
