/* Generated By:JJTree: Do not edit this line. ASTfloating_pt_type.cs */

using System;

namespace parser {

public class ASTfloating_pt_type : SimpleNode {
  public ASTfloating_pt_type(int id) : base(id) {
  }

  public ASTfloating_pt_type(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return ((SimpleNode)jjtGetChild(0)).GetIdentification();
  }

}


}

