/* Generated By:JJTree: Do not edit this line. ASTfloating_pt_type_float.cs */

using System;

namespace parser {

public class ASTfloating_pt_type_float : SimpleNode {
  public ASTfloating_pt_type_float(int id) : base(id) {
  }

  public ASTfloating_pt_type_float(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "float";
  }

}


}

