/* Generated By:JJTree: Do not edit this line. ASTforward_dcl.java */

package parser;

public class ASTforward_dcl extends SimpleNodeWithIdent {
  public ASTforward_dcl(int id) {
    super(id);
  }

  public ASTforward_dcl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  private boolean m_isAbstract = false;
  public boolean isAbstract() {
    return m_isAbstract;
  }
  public void setAbstract(boolean isAbstract) {
      m_isAbstract = isAbstract;
  }
}
