/* Generated By:JJTree: Do not edit this line. ASTfixed_pt_type.java */

package parser;

public class ASTfixed_pt_type extends SimpleNode {
  public ASTfixed_pt_type(int id) {
    super(id);
  }

  public ASTfixed_pt_type(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
