/* Generated By:JJTree: Do not edit this line. ASTfloating_pt_type_double.cs */

using System;

namespace parser {

public class ASTfloating_pt_type_double : SimpleNode {
  public ASTfloating_pt_type_double(int id) : base(id) {
  }

  public ASTfloating_pt_type_double(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "double";
  }

}


}

