/* Generated By:JJTree: Do not edit this line. ASTfloating_pt_type_double.java */

package parser;

public class ASTfloating_pt_type_double extends SimpleNode {
  public ASTfloating_pt_type_double(int id) {
    super(id);
  }

  public ASTfloating_pt_type_double(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
