/* Generated By:JJTree: Do not edit this line. ASTinterface_header.cs */

/* ASTinterface_header.cs
 * 
 * Project: IIOP.NET
 * IDLToCLSCompiler
 * 
 * WHEN      RESPONSIBLE
 * 14.02.03  Dominic Ullmann (DUL), dominic.ullmann -at- elca.ch
 *  
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

using System;
using System.Collections;

namespace parser {

public class ASTinterface_header : SimpleNodeWithIdent {

    #region IFields
    
    private bool m_isAbstract = false;

    private bool m_isLocal = false;
    
    #endregion IFields
    #region IConstructors

    public ASTinterface_header(int id) : base(id) {
    }

    public ASTinterface_header(IDLParser p, int id) : base(p, id) {
    }

    #endregion IConstructors
    #region IMethods

    /** Accept the visitor. **/
    public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public bool isAbstract() {
        return m_isAbstract;
    }
  
    /** make sure to set either abstract or local or none, but not abstract and local */
    public void setAbstract() {
        m_isAbstract = true;
    }

    public bool isLocal() {
        return m_isLocal;
    }
  
    /** make sure to set either abstract or local or none, but not abstract and local */
    public void setLocal() {
        m_isLocal = true;
    }
    
    public IList getInheritedScopeNames() {
        if (jjtGetNumChildren() > 0) {
            // an inheritance spec available
            ASTinterface_inheritance_spec inheritanceSpec = 
                (ASTinterface_inheritance_spec) jjtGetChild(0);
            return inheritanceSpec.getInheritedScopeNames();
        } else {
            return new ArrayList();
        }
    }
    
    public override string GetIdentification() {
        return "interface " + getIdent();
    }
    
    public override string GetEmbedderDesc() {
        return ((SimpleNode)jjtGetParent()).GetEmbedderDesc();
    }
    
    #endregion IMethods
    
}
}
