/* Generated By:JJTree: Do not edit this line. ASTinterface_name.java */

package parser;

public class ASTinterface_name extends SimpleNode {
  public ASTinterface_name(int id) {
    super(id);
  }

  public ASTinterface_name(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

}
