/* Generated By:JJTree: Do not edit this line. ASTinteger_type.java */

package parser;

public class ASTinteger_type extends SimpleNode {
  public ASTinteger_type(int id) {
    super(id);
  }

  public ASTinteger_type(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
