/* Generated By:JJTree: Do not edit this line. ASTinit_param_decl.java */

package parser;

public class ASTinit_param_decl extends SimpleNode {
  public ASTinit_param_decl(int id) {
    super(id);
  }

  public ASTinit_param_decl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
