/* Generated By:JJTree: Do not edit this line. ASTinterface_dcl.cs */

using System;

namespace parser {

public class ASTinterface_dcl : SimpleNode {
  public ASTinterface_dcl(int id) : base(id) {
  }

  public ASTinterface_dcl(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return ((SimpleNode)jjtGetChild(0)).GetIdentification() + 
        " (in " + ((SimpleNode)jjtGetParent()).GetEmbedderDesc() + ")";
  }
  
  public override string GetEmbedderDesc() {
    return ((SimpleNodeWithIdent)jjtGetChild(0)).getIdent() + 
        " (in " + ((SimpleNode)jjtGetParent()).GetEmbedderDesc() + ")";
  }

}


}

