/* Generated By:JJTree: Do not edit this line. ASTinteger_type.cs */

using System;

namespace parser {

public class ASTinteger_type : SimpleNode {
  public ASTinteger_type(int id) : base(id) {
  }

  public ASTinteger_type(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return ((SimpleNode)jjtGetChild(0)).GetIdentification();
  }

}


}

