/* Generated By:JJTree: Do not edit this line. ASTliteral.java */

package parser;

public class ASTliteral extends SimpleNode {
  public ASTliteral(int id) {
    super(id);
  }

  public ASTliteral(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  
  private Object m_litVal;
  public void setLitVal(Object litVal) {
      m_litVal = litVal;
  }
  public Object getLitVal() {
      return m_litVal;
  }
}
