/* Generated By:JJTree: Do not edit this line. ASTmember.java */

package parser;

public class ASTmember extends SimpleNode {
  public ASTmember(int id) {
    super(id);
  }

  public ASTmember(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
