/* Generated By:JJTree: Do not edit this line. ASTmodule.java */

package parser;

public class ASTmodule extends SimpleNodeWithIdent {
  public ASTmodule(int id) {
    super(id);
  }

  public ASTmodule(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
