/* Generated By:JJTree: Do not edit this line. ASTmember.cs */

using System;

namespace parser {

public class ASTmember : SimpleNode {
  public ASTmember(int id) : base(id) {
  }

  public ASTmember(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    string memberNameList =
      ((SimpleNode)jjtGetChild(1)).GetIdentification();
        
    return "member(s) " + memberNameList +
           " defined in " +
           ((SimpleNode)jjtGetParent()).GetEmbedderDesc();    
  }
  
}


}

