/* Generated By:JJTree: Do not edit this line. ASTmember_list.java */

package parser;

public class ASTmember_list extends SimpleNode {
  public ASTmember_list(int id) {
    super(id);
  }

  public ASTmember_list(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
