/* Generated By:JJTree: Do not edit this line. ASTobject_type.cs */

using System;

namespace parser {

public class ASTobject_type : SimpleNode {
  public ASTobject_type(int id) : base(id) {
  }

  public ASTobject_type(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {      
    return "Object";
  }  

}


}

