/* Generated By:JJTree: Do not edit this line. ASTop_type_spec.cs */

using System;

namespace parser {

public class ASTop_type_spec : SimpleNode {
  public ASTop_type_spec(int id) : base(id) {
  }

  public ASTop_type_spec(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
     return "return parameter in " +
             ((SimpleNode)jjtGetParent()).GetEmbedderDesc();
  }
  
}


}

