/* Generated By:JJTree: Do not edit this line. ASTop_dcl.java */

package parser;

public class ASTop_dcl extends SimpleNodeWithIdent {
  public ASTop_dcl(int id) {
    super(id);
  }

  public ASTop_dcl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public final static int OP_Attr_NONE = 0;
  public final static int OP_Attr_ONEWAY = 1;

  private int m_opAttr = OP_Attr_NONE;
  public void setOpAttr(int opAttr) {
    if ((opAttr < OP_Attr_NONE) || (opAttr > OP_Attr_ONEWAY)) { throw new RuntimeException("invalid opAttr: " + opAttr); }
    m_opAttr = opAttr;
  }

  public int getOpAttr() {
    return m_opAttr;
  }
}
