/* Generated By:JJTree: Do not edit this line. ASTparam_attribute.java */

package parser;

public class ASTparam_attribute extends SimpleNode {
  public ASTparam_attribute(int id) {
    super(id);
  }

  public ASTparam_attribute(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public static final int ParamDir_IN = 0;
  public static final int ParamDir_OUT = 1;
  public static final int ParamDir_INOUT = 2;
    
  private int m_paramDir = ParamDir_IN;

  public boolean isInOut() {
    return (m_paramDir == ParamDir_INOUT);
  }

  public boolean isOut() {
    return (m_paramDir == ParamDir_OUT);
  }

  public boolean isIn() {
    return (m_paramDir == ParamDir_IN);
  }
  
  public void setParamDir(int paramDir) {
    if ((paramDir < ParamDir_IN) || (paramDir > ParamDir_INOUT)) {
        throw new RuntimeException("invalid parameter direction: " + paramDir);
    }
    m_paramDir = paramDir;
  }

  public int getParamDir() {
      return m_paramDir;
  }
}
