/* Generated By:JJTree: Do not edit this line. ASTparameter_dcls.java */

package parser;

public class ASTparameter_dcls extends SimpleNode {
  public ASTparameter_dcls(int id) {
    super(id);
  }

  public ASTparameter_dcls(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
