/* Generated By:JJTree: Do not edit this line. ASTpositive_int_const.java */

package parser;

public class ASTpositive_int_const extends SimpleNode {
  public ASTpositive_int_const(int id) {
    super(id);
  }

  public ASTpositive_int_const(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
