/* Generated By:JJTree: Do not edit this line. ASTparam_attribute.java */

/* ASTparam_attribute.java
 * 
 * Project: IIOP.NET
 * IDLToCLSCompiler
 * 
 * WHEN      RESPONSIBLE
 * 14.02.03  Dominic Ullmann (DUL), dul@elca.ch
 *  
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package parser;

public class ASTparam_attribute extends SimpleNode {

    #region Constants

    public static final int ParamDir_IN = 0;
    public static final int ParamDir_OUT = 1;
    public static final int ParamDir_INOUT = 2;

    #endregion Constants
    #region IFields
    
    private int m_paramDir = ParamDir_IN;
    
    #endregion IFields
    #region IConstructors

    public ASTparam_attribute(int id) {
        super(id);
    }

    public ASTparam_attribute(IDLParser p, int id) {
        super(p, id);
    }
    
    #endregion IConstructors
    #region IMethods

    /** Accept the visitor. **/
    public Object jjtAccept(IDLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public boolean isInOut() {
        return (m_paramDir == ParamDir_INOUT);
    }

    public boolean isOut() {
        return (m_paramDir == ParamDir_OUT);
    }

    public boolean isIn() {
        return (m_paramDir == ParamDir_IN);
    }
  
    public void setParamDir(int paramDir) {
        if ((paramDir < ParamDir_IN) || (paramDir > ParamDir_INOUT)) {
            throw new RuntimeException("invalid parameter direction: " + paramDir);
        }
        m_paramDir = paramDir;
    }

    public int getParamDir() {
        return m_paramDir;
    }
    
    #endregion IMethods

}
