/* Generated By:JJTree: Do not edit this line. ASTsequence_type.cs */

using System;

namespace parser {

public class ASTsequence_type : SimpleNode {
  public ASTsequence_type(int id) : base(id) {
  }

  public ASTsequence_type(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {      
    return "sequence with element type " + 
      ((SimpleNode)jjtGetChild(0)).GetIdentification();
  }
  
}


}

