/* Generated By:JJTree: Do not edit this line. ASTswitch_body.java */

package parser;

public class ASTswitch_body extends SimpleNode {
  public ASTswitch_body(int id) {
    super(id);
  }

  public ASTswitch_body(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
