/* Generated By:JJTree: Do not edit this line. ASTstate_member.java */

package parser;

public class ASTstate_member extends SimpleNode {
  public ASTstate_member(int id) {
    super(id);
  }

  public ASTstate_member(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  private boolean m_isPrivate = false;
  public boolean isPrivate() {
      return m_isPrivate;
  }

  public void setIsPrivate(boolean isPrivate) {
      m_isPrivate = isPrivate;
  }

}
