/* Generated By:JJTree: Do not edit this line. ASTstate_member.java */

/* ASTstate_member.java
 * 
 * Project: IIOP.NET
 * IDLToCLSCompiler
 * 
 * WHEN      RESPONSIBLE
 * 14.02.03  Dominic Ullmann (DUL), dul@elca.ch
 *  
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package parser;

public class ASTstate_member extends SimpleNode {

    #region IFields
    
    private boolean m_isPrivate = false;
    
    #endregion IFields
    #region IConstructors

    public ASTstate_member(int id) {
        super(id);
    }

    public ASTstate_member(IDLParser p, int id) {
        super(p, id);
    }

    #endregion IConstructors
    #region IMethods

    /** Accept the visitor. **/
    public Object jjtAccept(IDLParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
  
    public boolean isPrivate() {
        return m_isPrivate;
    }

    public void setIsPrivate(boolean isPrivate) {
        m_isPrivate = isPrivate;
    }
    
    #endregion IMethods

}
