/* Generated By:JJTree: Do not edit this line. ASTsimple_type_spec.java */

package parser;

public class ASTsimple_type_spec extends SimpleNode {
  public ASTsimple_type_spec(int id) {
    super(id);
  }

  public ASTsimple_type_spec(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
