/* Generated By:JJTree: Do not edit this line. ASTsimple_declarator.java */

package parser;

public class ASTsimple_declarator extends SimpleNodeWithIdent {
  public ASTsimple_declarator(int id) {
    super(id);
  }

  public ASTsimple_declarator(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
