/* Generated By:JJTree: Do not edit this line. ASTspecification.java */

package parser;

public class ASTspecification extends SimpleNode {
  public ASTspecification(int id) {
    super(id);
  }

  public ASTspecification(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
