/* Generated By:JJTree: Do not edit this line. ASTsequence_type.java */

package parser;

public class ASTsequence_type extends SimpleNode {
  public ASTsequence_type(int id) {
    super(id);
  }

  public ASTsequence_type(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
