/* Generated By:JJTree: Do not edit this line. ASTscoped_name.java */

package parser;

import java.util.LinkedList;

public class ASTscoped_name extends SimpleNode {
  public ASTscoped_name(int id) {
    super(id);
  }

  public ASTscoped_name(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  private LinkedList m_nameParts = new LinkedList();
  public LinkedList getNameParts() {
      return m_nameParts;
  }
  
  public void addNamePart(String namePart) {
      m_nameParts.add(namePart);
  }

  private boolean m_hasFileScope = false;
  public boolean hasFileScope() {
    return m_hasFileScope;
  }
  public void setHasFileScope(boolean hasFileScope) {
    m_hasFileScope = hasFileScope;
  }


  private String m_scopedName;
  public void setScopedName(String scopedName) {
    m_scopedName = scopedName;
  }
    
  /** returns the CORBA scoped name represented by this node */
  public String getScopedName() {
    return m_scopedName;
  }

}
