/* Generated By:JJTree: Do not edit this line. ASTtype_dcl.java */

package parser;

public class ASTtype_dcl extends SimpleNode {
  public ASTtype_dcl(int id) {
    super(id);
  }

  public ASTtype_dcl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
