/* Generated By:JJTree: Do not edit this line. ASTtype_declarator.cs */

using System;

namespace parser {

public class ASTtype_declarator : SimpleNode {
  public ASTtype_declarator(int id) : base(id) {
  }

  public ASTtype_declarator(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "typedef for type " + 
      ((SimpleNode)jjtGetChild(0)).GetIdentification();
  }

}


}

