/* Generated By:JJTree: Do not edit this line. ASTtype_declarator.java */

package parser;

public class ASTtype_declarator extends SimpleNode {
  public ASTtype_declarator(int id) {
    super(id);
  }

  public ASTtype_declarator(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
