/* Generated By:JJTree: Do not edit this line. ASTtype_spec.cs */

using System;

namespace parser {

public class ASTtype_spec : SimpleNode {
  public ASTtype_spec(int id) : base(id) {
  }

  public ASTtype_spec(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return ((SimpleNode)jjtGetChild(0)).GetIdentification();
  }

}


}

