/* Generated By:JJTree: Do not edit this line. ASTunary_expr.java */

package parser;

public class ASTunary_expr extends SimpleNode {
  public ASTunary_expr(int id) {
    super(id);
  }

  public ASTunary_expr(IDLParser p, int id) {
    super(p, id);
  }

  /** operator constant for no unary operator specified */
  public static final int UNARY_NONE = 0;
  /** operator constant for unary minus */
  public static final int UNARY_MINUS = 1;
  /** operator constant for unary plus */
  public static final int UNARY_PLUS = 2;
  /** operator constant for unary negate */
  public static final int UNARY_NEGATE = 3;


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
