/* Generated By:JJTree: Do not edit this line. ASTunsigned_long_int.java */

package parser;

public class ASTunsigned_long_int extends SimpleNode {
  public ASTunsigned_long_int(int id) {
    super(id);
  }

  public ASTunsigned_long_int(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
