/* Generated By:JJTree: Do not edit this line. ASTunsigned_long_int.cs */

using System;

namespace parser {

public class ASTunsigned_long_int : SimpleNode {
  public ASTunsigned_long_int(int id) : base(id) {
  }

  public ASTunsigned_long_int(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {
    return "ulong";
  }
}


}

