/* Generated By:JJTree: Do not edit this line. ASTvalue_base_inheritance_spec.java */

package parser;

public class ASTvalue_base_inheritance_spec extends SimpleNode {
  public ASTvalue_base_inheritance_spec(int id) {
    super(id);
  }

  public ASTvalue_base_inheritance_spec(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
