/* Generated By:JJTree: Do not edit this line. ASTvalue_base_type.java */

package parser;

public class ASTvalue_base_type extends SimpleNode {
  public ASTvalue_base_type(int id) {
    super(id);
  }

  public ASTvalue_base_type(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
