/* Generated By:JJTree: Do not edit this line. ASTvalue_abs_decl.java */

package parser;

public class ASTvalue_abs_decl extends SimpleNodeWithIdent {
  public ASTvalue_abs_decl(int id) {
    super(id);
  }

  public ASTvalue_abs_decl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
