/* Generated By:JJTree: Do not edit this line. ASTvalue.java */

package parser;

public class ASTvalue extends SimpleNode {
  public ASTvalue(int id) {
    super(id);
  }

  public ASTvalue(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
