/* Generated By:JJTree: Do not edit this line. ASTvalue_name.java */

package parser;

public class ASTvalue_name extends SimpleNode {
  public ASTvalue_name(int id) {
    super(id);
  }

  public ASTvalue_name(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
