/* Generated By:JJTree: Do not edit this line. ASTvalue.cs */

using System;

namespace parser {

public class ASTvalue : SimpleNode {
  public ASTvalue(int id) : base(id) {
  }

  public ASTvalue(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public override string GetIdentification() {      
    return ((SimpleNode)jjtGetChild(0)).GetIdentification();      
  }
  
  public override string GetEmbedderDesc() {
    // is called by children for the defined in part
    return ((SimpleNode)jjtGetParent()).GetEmbedderDesc();
  }
  
}


}

