/* Generated By:JJTree: Do not edit this line. ASTvalue_support_inheritance_spec.cs */

using System;

namespace parser {

public class ASTvalue_support_inheritance_spec : SimpleNode {
  public ASTvalue_support_inheritance_spec(int id) : base(id) {
  }

  public ASTvalue_support_inheritance_spec(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

