/* Generated By:JJTree: Do not edit this line. ASTvalue_forward_decl.java */

package parser;

public class ASTvalue_forward_decl extends SimpleNodeWithIdent {
  public ASTvalue_forward_decl(int id) {
    super(id);
  }

  public ASTvalue_forward_decl(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  private boolean m_isAbstract = false;
  public boolean isAbstract() {
    return m_isAbstract;
  }
  public void setAbstract(boolean isAbstract) {
      m_isAbstract = isAbstract;
  }
}
