/* Generated By:JJTree: Do not edit this line. ASTvalue_header.java */

package parser;

public class ASTvalue_header extends SimpleNodeWithIdent {
  public ASTvalue_header(int id) {
    super(id);
  }

  public ASTvalue_header(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  private boolean m_isCustom;
  public boolean isCustom() {
      return m_isCustom;
  }
  public void setCustom(boolean isCustom) {
      m_isCustom = isCustom;
  }
}
