/* Generated By:JJTree: Do not edit this line. ASTwide_char_type.java */

package parser;

public class ASTwide_char_type extends SimpleNode {
  public ASTwide_char_type(int id) {
    super(id);
  }

  public ASTwide_char_type(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
