/* Generated By:JJTree: Do not edit this line. ASTxor_expr.java */

package parser;

public class ASTxor_expr extends SimpleNode {
  public ASTxor_expr(int id) {
    super(id);
  }

  public ASTxor_expr(IDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
