/* Generated By:JavaCC: Do not edit this line. Error.cs Version 3.0 */
using System;

/**
 * exception class for critical exceptions
 */

public class Error : Exception {

  public Error(string msg) : base (msg) { }
  public Error() : base() { }

}
