/* Generated By:JJTree&JavaCC: Do not edit this line. IDLParserTokenManager.cs */
using System;
using System.Diagnostics;


public class IDLParserTokenManager
{
private int jjStopStringLiteralDfa_0(int pos, ulong active0, ulong active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40000000000000L) != (ulong)0L || (active1 & 0x19000010L) != (ulong)0L)
            return 13;
         if ((active1 & 0x4000000L) != (ulong)0L)
            return 15;
         if ((active0 & 0x1000L) != (ulong)0L)
            return 85;
         if ((active0 & 0xffbe001cfe396000L) != (ulong)0L || (active1 & 0x2ffe66fL) != (ulong)0L)
         {
            jjmatchedKind = 93;
            return 13;
         }
         return -1;
      case 1:
         if ((active0 & 0xfffe0018fe314000L) != (ulong)0L || (active1 & 0x2f7e67fL) != (ulong)0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return 13;
         }
         if ((active0 & 0x400082000L) != (ulong)0L || (active1 & 0x80000L) != (ulong)0L)
            return 13;
         return -1;
      case 2:
         if ((active0 & 0xbffe0008fe394000L) != (ulong)0L || (active1 & 0x2fbe67fL) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 2;
            return 13;
         }
         if ((active0 & 0x4000001000000000L) != (ulong)0L || (active1 & 0x40000L) != (ulong)0L)
            return 13;
         return -1;
      case 3:
         if ((active0 & 0x482000000000000L) != (ulong)0L || (active1 & 0x20028L) != (ulong)0L)
            return 13;
         if ((active0 & 0xbb7c0008fe394000L) != (ulong)0L || (active1 & 0x2f9e657L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 3;
            return 13;
         }
         return -1;
      case 4:
         if ((active0 & 0x92580000fe194000L) != (ulong)0L || (active1 & 0x2b1e655L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 4;
            return 13;
         }
         if ((active0 & 0x2924000800200000L) != (ulong)0L || (active1 & 0x480002L) != (ulong)0L)
            return 13;
         return -1;
      case 5:
         if ((active0 & 0x12080000da180000L) != (ulong)0L || (active1 & 0x2a0e450L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 5;
            return 13;
         }
         if ((active0 & 0x8050000024014000L) != (ulong)0L || (active1 & 0x110205L) != (ulong)0L)
            return 13;
         return -1;
      case 6:
         if ((active0 & 0x10080000c0000000L) != (ulong)0L || (active1 & 0x200410L) != (ulong)0L)
            return 13;
         if ((active0 & 0x20000001a180000L) != (ulong)0L || (active1 & 0x280e040L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 6;
            return 13;
         }
         return -1;
      case 7:
         if ((active0 & 0xa080000L) != (ulong)0L || (active1 & 0x80c000L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 7;
            return 13;
         }
         if ((active0 & 0x200000010100000L) != (ulong)0L || (active1 & 0x2002040L) != (ulong)0L)
            return 13;
         return -1;
      case 8:
         if ((active0 & 0x8000000L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 8;
            return 13;
         }
         if ((active0 & 0x2080000L) != (ulong)0L || (active1 & 0x80c000L) != (ulong)0L)
            return 13;
         return -1;
      case 9:
         if ((active0 & 0x8000000L) != (ulong)0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 9;
            return 13;
         }
         return -1;
      default :
         return -1;
   }
}
private int jjStartNfa_0(int pos, ulong active0, ulong active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, (ulong)active0, (ulong)active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case ((char) 35):
         return jjMoveStringLiteralDfa1_0((ulong)0x1000L, (ulong)0x0L);
      case ((char) 37):
         return jjStopAtPos(0, 47);
      case ((char) 38):
         return jjStopAtPos(0, 40);
      case ((char) 40):
         return jjStopAtPos(0, 32);
      case ((char) 41):
         return jjStopAtPos(0, 33);
      case ((char) 42):
         return jjStopAtPos(0, 45);
      case ((char) 43):
         return jjStopAtPos(0, 43);
      case ((char) 44):
         return jjStopAtPos(0, 23);
      case ((char) 45):
         return jjStopAtPos(0, 44);
      case ((char) 46):
         return jjStartNfaWithStates_0(0, 90, 15);
      case ((char) 47):
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0((ulong)0x60L, (ulong)0x0L);
      case ((char) 58):
         jjmatchedKind = 22;
         return jjMoveStringLiteralDfa1_0((ulong)0x1000000L, (ulong)0x0L);
      case ((char) 59):
         return jjStopAtPos(0, 15);
      case ((char) 60):
         jjmatchedKind = 71;
         return jjMoveStringLiteralDfa1_0((ulong)0x40000000000L, (ulong)0x0L);
      case ((char) 61):
         return jjStopAtPos(0, 37);
      case ((char) 62):
         jjmatchedKind = 72;
         return jjMoveStringLiteralDfa1_0((ulong)0x20000000000L, (ulong)0x0L);
      case ((char) 68):
         return jjStartNfaWithStates_0(0, 92, 13);
      case ((char) 70):
         return jjMoveStringLiteralDfa1_0((ulong)0x4000000000000L, (ulong)0x0L);
      case ((char) 73):
         return jjMoveStringLiteralDfa1_0((ulong)0x2000L, (ulong)0x2000000L);
      case ((char) 76):
         return jjStartNfaWithStates_0(0, 88, 13);
      case ((char) 78):
         return jjMoveStringLiteralDfa1_0((ulong)0x1000000000L, (ulong)0x0L);
      case ((char) 79):
         return jjMoveStringLiteralDfa1_0((ulong)0x8000000000000000L, (ulong)0x0L);
      case ((char) 84):
         return jjMoveStringLiteralDfa1_0((ulong)0x2000000000000L, (ulong)0x0L);
      case ((char) 86):
         return jjMoveStringLiteralDfa1_0((ulong)0x0L, (ulong)0x800000L);
      case ((char) 91):
         return jjStopAtPos(0, 75);
      case ((char) 93):
         return jjStopAtPos(0, 76);
      case ((char) 94):
         return jjStopAtPos(0, 39);
      case ((char) 97):
         return jjMoveStringLiteralDfa1_0((ulong)0x4000000000100000L, (ulong)0x4000L);
      case ((char) 98):
         return jjMoveStringLiteralDfa1_0((ulong)0x1000000000000000L, (ulong)0x0L);
      case ((char) 99):
         return jjMoveStringLiteralDfa1_0((ulong)0x400000804000000L, (ulong)0x200008L);
      case ((char) 100):
         jjmatchedKind = 91;
         return jjMoveStringLiteralDfa1_0((ulong)0x40000000000000L, (ulong)0x10L);
      case ((char) 101):
         return jjMoveStringLiteralDfa1_0((ulong)0x0L, (ulong)0x8020L);
      case ((char) 102):
         return jjMoveStringLiteralDfa1_0((ulong)0x20000080000000L, (ulong)0x400000L);
      case ((char) 105):
         return jjMoveStringLiteralDfa1_0((ulong)0x400080000L, (ulong)0x80000L);
      case ((char) 108):
         return jjMoveStringLiteralDfa1_0((ulong)0x80000000200000L, (ulong)0x0L);
      case ((char) 109):
         return jjMoveStringLiteralDfa1_0((ulong)0x10000L, (ulong)0x0L);
      case ((char) 110):
         return jjMoveStringLiteralDfa1_0((ulong)0x10000000000000L, (ulong)0x0L);
      case ((char) 111):
         return jjMoveStringLiteralDfa1_0((ulong)0x2000000000000000L, (ulong)0x50000L);
      case ((char) 112):
         return jjMoveStringLiteralDfa1_0((ulong)0x60004000L, (ulong)0x0L);
      case ((char) 114):
         return jjMoveStringLiteralDfa1_0((ulong)0x0L, (ulong)0x102000L);
      case ((char) 115):
         return jjMoveStringLiteralDfa1_0((ulong)0x100000010000000L, (ulong)0x245L);
      case ((char) 116):
         return jjMoveStringLiteralDfa1_0((ulong)0x8000008000000L, (ulong)0x0L);
      case ((char) 117):
         return jjMoveStringLiteralDfa1_0((ulong)0x200000000000000L, (ulong)0x2L);
      case ((char) 118):
         return jjMoveStringLiteralDfa1_0((ulong)0x2000000L, (ulong)0x20000L);
      case ((char) 119):
         return jjMoveStringLiteralDfa1_0((ulong)0x800000000000000L, (ulong)0x400L);
      case ((char) 123):
         return jjStopAtPos(0, 17);
      case ((char) 124):
         return jjStopAtPos(0, 38);
      case ((char) 125):
         return jjStopAtPos(0, 18);
      case ((char) 126):
         return jjStopAtPos(0, 48);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(ulong active0, ulong active1)
{
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(0, (ulong)active0, (ulong)active1);
      return 1;
   }
   switch(curChar)
   {
      case ((char) 42):
         if ((active0 & 0x40L) != (ulong)0L)
            return jjStopAtPos(1, 6);
         break;
      case ((char) 47):
         if ((active0 & 0x20L) != (ulong)0L)
            return jjStopAtPos(1, 5);
         break;
      case ((char) 58):
         if ((active0 & 0x1000000L) != (ulong)0L)
            return jjStopAtPos(1, 24);
         break;
      case ((char) 60):
         if ((active0 & 0x40000000000L) != (ulong)0L)
            return jjStopAtPos(1, 42);
         break;
      case ((char) 62):
         if ((active0 & 0x20000000000L) != (ulong)0L)
            return jjStopAtPos(1, 41);
         break;
      case ((char) 65):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x4000000000000L, active1, (ulong)0L);
      case ((char) 68):
         if ((active0 & 0x2000L) != (ulong)0L)
            return jjStartNfaWithStates_0(1, 13, 13);
         break;
      case ((char) 82):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x2000000000000L, active1, (ulong)0L);
      case ((char) 97):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x10001082000000L, active1, (ulong)0x900008L);
      case ((char) 98):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x8000000000100000L, active1, (ulong)0L);
      case ((char) 99):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x2800000000000000L, active1, (ulong)0L);
      case ((char) 101):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0L, active1, (ulong)0x2050L);
      case ((char) 104):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x500000000000000L, active1, (ulong)0L);
      case ((char) 105):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0L, active1, (ulong)0x400000L);
      case ((char) 108):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x20000000000000L, active1, (ulong)0L);
      case ((char) 110):
         if ((active0 & 0x400000000L) != (ulong)0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x4200000000080000L, active1, (ulong)0x2090022L);
      case ((char) 111):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x10c0000800210000L, active1, (ulong)0x220000L);
      case ((char) 112):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x1000L, active1, (ulong)0L);
      case ((char) 114):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x48004000L, active1, (ulong)0L);
      case ((char) 115):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0L, active1, (ulong)0x400L);
      case ((char) 116):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0L, active1, (ulong)0x4201L);
      case ((char) 117):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x34000000L, active1, (ulong)0x40000L);
      case ((char) 119):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0L, active1, (ulong)0x4L);
      case ((char) 120):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0L, active1, (ulong)0x8000L);
      case ((char) 121):
         return jjMoveStringLiteralDfa2_0(active0, (ulong)0x8000000000000L, active1, (ulong)0L);
      default :
         break;
   }
   return jjStartNfa_0(0, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa2_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(0, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(1, (ulong)active0, (ulong)active1);
      return 2;
   }
   switch(curChar)
   {
      case ((char) 76):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x4000000000000L, active1, (ulong)0L);
      case ((char) 78):
         if ((active0 & 0x1000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(2, 36, 13);
         break;
      case ((char) 85):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x2000000000000L, active1, (ulong)0L);
      case ((char) 97):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x400000000000000L, active1, (ulong)0x2000L);
      case ((char) 98):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x20000000L, active1, (ulong)0L);
      case ((char) 99):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x80200000L, active1, (ulong)0x8000L);
      case ((char) 100):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x10000L, active1, (ulong)0L);
      case ((char) 101):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x4000L, active1, (ulong)0x10000L);
      case ((char) 102):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0L, active1, (ulong)0x2000010L);
      case ((char) 104):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x800000000000000L, active1, (ulong)0L);
      case ((char) 105):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x40000000L, active1, (ulong)0x120006L);
      case ((char) 106):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x8000000000000000L, active1, (ulong)0L);
      case ((char) 108):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x2000000L, active1, (ulong)0x800000L);
      case ((char) 110):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x80000800000000L, active1, (ulong)0x200000L);
      case ((char) 111):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x1120000000000000L, active1, (ulong)0x80000L);
      case ((char) 112):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x8000010000000L, active1, (ulong)0L);
      case ((char) 113):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0L, active1, (ulong)0x40L);
      case ((char) 114):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x1000L, active1, (ulong)0x201L);
      case ((char) 115):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x200000004100000L, active1, (ulong)0x8L);
      case ((char) 116):
         if ((active1 & 0x40000L) != (ulong)0L)
            return jjStartNfaWithStates_0(2, 82, 13);
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x2010000000080000L, active1, (ulong)0x4400L);
      case ((char) 117):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0x40000008000000L, active1, (ulong)0x20L);
      case ((char) 120):
         return jjMoveStringLiteralDfa3_0(active0, (ulong)0L, active1, (ulong)0x400000L);
      case ((char) 121):
         if ((active0 & 0x4000000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(2, 62, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa3_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(1, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(2, (ulong)active0, (ulong)active1);
      return 3;
   }
   switch(curChar)
   {
      case ((char) 69):
         if ((active0 & 0x2000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(3, 49, 13);
         break;
      case ((char) 83):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x4000000000000L, active1, (ulong)0L);
      case ((char) 97):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x820000000201000L, active1, (ulong)0x10L);
      case ((char) 98):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x40000000000000L, active1, (ulong)0L);
      case ((char) 100):
         if ((active1 & 0x20000L) != (ulong)0L)
            return jjStartNfaWithStates_0(3, 81, 13);
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0L, active1, (ulong)0x2000L);
      case ((char) 101):
         if ((active1 & 0x8L) != (ulong)0L)
            return jjStartNfaWithStates_0(3, 67, 13);
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0xa008000000080000L, active1, (ulong)0x408000L);
      case ((char) 102):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x4000L, active1, (ulong)0L);
      case ((char) 103):
         if ((active0 & 0x80000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(3, 55, 13);
         break;
      case ((char) 105):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x210000000000000L, active1, (ulong)0x2000200L);
      case ((char) 108):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x1000000020000000L, active1, (ulong)0L);
      case ((char) 109):
         if ((active1 & 0x20L) != (ulong)0L)
            return jjStartNfaWithStates_0(3, 69, 13);
         break;
      case ((char) 110):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x8000000L, active1, (ulong)0L);
      case ((char) 111):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0L, active1, (ulong)0x2L);
      case ((char) 112):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x10000000L, active1, (ulong)0L);
      case ((char) 114):
         if ((active0 & 0x400000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(3, 58, 13);
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x100000000000000L, active1, (ulong)0x4400L);
      case ((char) 115):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x800000000L, active1, (ulong)0x100000L);
      case ((char) 116):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x84100000L, active1, (ulong)0x200004L);
      case ((char) 117):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x2010000L, active1, (ulong)0x880041L);
      case ((char) 118):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0x40000000L, active1, (ulong)0L);
      case ((char) 119):
         return jjMoveStringLiteralDfa4_0(active0, (ulong)0L, active1, (ulong)0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(2, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa4_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(2, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(3, (ulong)active0, (ulong)active1);
      return 4;
   }
   switch(curChar)
   {
      case ((char) 69):
         if ((active0 & 0x4000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 50, 13);
         break;
      case ((char) 97):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x40000000L, active1, (ulong)0x10000L);
      case ((char) 99):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x8000000008000000L, active1, (ulong)0x5L);
      case ((char) 100):
         if ((active1 & 0x400000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 86, 13);
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x8000000000000L, active1, (ulong)0L);
      case ((char) 101):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x1000000002000000L, active1, (ulong)0xb00040L);
      case ((char) 103):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x200000000001000L, active1, (ulong)0L);
      case ((char) 105):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x20004000L, active1, (ulong)0x4400L);
      case ((char) 108):
         if ((active0 & 0x200000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 21, 13);
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x40000000010000L, active1, (ulong)0L);
      case ((char) 110):
         if ((active1 & 0x2L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 65, 13);
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0L, active1, (ulong)0x2000200L);
      case ((char) 111):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x94000000L, active1, (ulong)0x2000L);
      case ((char) 112):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0L, active1, (ulong)0x8000L);
      case ((char) 114):
         if ((active0 & 0x800000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 59, 13);
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x180000L, active1, (ulong)0L);
      case ((char) 116):
         if ((active0 & 0x800000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 35, 13);
         else if ((active0 & 0x20000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 53, 13);
         else if ((active0 & 0x100000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 56, 13);
         else if ((active0 & 0x2000000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 61, 13);
         else if ((active1 & 0x80000L) != (ulong)0L)
            return jjStartNfaWithStates_0(4, 83, 13);
         break;
      case ((char) 117):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0L, active1, (ulong)0x10L);
      case ((char) 118):
         return jjMoveStringLiteralDfa5_0(active0, (ulong)0x10000000000000L, active1, (ulong)0L);
      default :
         break;
   }
   return jjStartNfa_0(3, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa5_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(3, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(4, (ulong)active0, (ulong)active1);
      return 5;
   }
   switch(curChar)
   {
      case ((char) 66):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0L, active1, (ulong)0x800000L);
      case ((char) 97):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x1000000008100000L, active1, (ulong)0L);
      case ((char) 98):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0L, active1, (ulong)0x4000L);
      case ((char) 99):
         if ((active0 & 0x20000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 29, 13);
         break;
      case ((char) 101):
         if ((active0 & 0x10000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 16, 13);
         else if ((active0 & 0x10000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 52, 13);
         else if ((active0 & 0x40000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 54, 13);
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x8000000000000L, active1, (ulong)0L);
      case ((char) 102):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x80000L, active1, (ulong)0L);
      case ((char) 103):
         if ((active1 & 0x200L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 73, 13);
         break;
      case ((char) 104):
         if ((active1 & 0x4L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 66, 13);
         break;
      case ((char) 105):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0L, active1, (ulong)0x2000000L);
      case ((char) 108):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0L, active1, (ulong)0x10L);
      case ((char) 109):
         if ((active0 & 0x4000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 26, 13);
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x1000L, active1, (ulong)0L);
      case ((char) 110):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x200000000000000L, active1, (ulong)0x2440L);
      case ((char) 114):
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x90000000L, active1, (ulong)0L);
      case ((char) 115):
         if ((active1 & 0x100000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 84, 13);
         break;
      case ((char) 116):
         if ((active0 & 0x8000000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 63, 13);
         else if ((active1 & 0x1L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 64, 13);
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0x42000000L, active1, (ulong)0x8000L);
      case ((char) 120):
         if ((active0 & 0x4000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 14, 13);
         return jjMoveStringLiteralDfa6_0(active0, (ulong)0L, active1, (ulong)0x200000L);
      case ((char) 121):
         if ((active1 & 0x10000L) != (ulong)0L)
            return jjStartNfaWithStates_0(5, 80, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa6_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(4, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(5, (ulong)active0, (ulong)active1);
      return 6;
   }
   switch(curChar)
   {
      case ((char) 97):
         if ((active0 & 0x1000L) != (ulong)0L)
            return jjStopAtPos(6, 12);
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0x80000L, active1, (ulong)0x800000L);
      case ((char) 99):
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0x100000L, active1, (ulong)0x40L);
      case ((char) 101):
         if ((active0 & 0x40000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 30, 13);
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0x200000000000000L, active1, (ulong)0L);
      case ((char) 102):
         if ((active0 & 0x8000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 51, 13);
         break;
      case ((char) 103):
         if ((active1 & 0x400L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 74, 13);
         break;
      case ((char) 105):
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0L, active1, (ulong)0x8000L);
      case ((char) 108):
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0L, active1, (ulong)0x2000L);
      case ((char) 110):
         if ((active0 & 0x1000000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 60, 13);
         break;
      case ((char) 116):
         if ((active1 & 0x10L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 68, 13);
         else if ((active1 & 0x200000L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 85, 13);
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0x18000000L, active1, (ulong)0x2000000L);
      case ((char) 117):
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0L, active1, (ulong)0x4000L);
      case ((char) 121):
         if ((active0 & 0x80000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(6, 31, 13);
         return jjMoveStringLiteralDfa7_0(active0, (ulong)0x2000000L, active1, (ulong)0L);
      default :
         break;
   }
   return jjStartNfa_0(5, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa7_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(5, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(6, (ulong)active0, (ulong)active1);
      return 7;
   }
   switch(curChar)
   {
      case ((char) 97):
         return jjMoveStringLiteralDfa8_0(active0, (ulong)0x8000000L, active1, (ulong)0L);
      case ((char) 99):
         return jjMoveStringLiteralDfa8_0(active0, (ulong)0x80000L, active1, (ulong)0L);
      case ((char) 100):
         if ((active0 & 0x200000000000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(7, 57, 13);
         break;
      case ((char) 101):
         if ((active1 & 0x40L) != (ulong)0L)
            return jjStartNfaWithStates_0(7, 70, 13);
         break;
      case ((char) 111):
         return jjMoveStringLiteralDfa8_0(active0, (ulong)0L, active1, (ulong)0x8000L);
      case ((char) 112):
         return jjMoveStringLiteralDfa8_0(active0, (ulong)0x2000000L, active1, (ulong)0L);
      case ((char) 115):
         if ((active0 & 0x10000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(7, 28, 13);
         return jjMoveStringLiteralDfa8_0(active0, (ulong)0L, active1, (ulong)0x800000L);
      case ((char) 116):
         if ((active0 & 0x100000L) != (ulong)0L)
            return jjStartNfaWithStates_0(7, 20, 13);
         return jjMoveStringLiteralDfa8_0(active0, (ulong)0L, active1, (ulong)0x4000L);
      case ((char) 121):
         if ((active1 & 0x2000L) != (ulong)0L)
            return jjStartNfaWithStates_0(7, 77, 13);
         else if ((active1 & 0x2000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(7, 89, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa8_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(6, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(7, (ulong)active0, (ulong)active1);
      return 8;
   }
   switch(curChar)
   {
      case ((char) 98):
         return jjMoveStringLiteralDfa9_0(active0, (ulong)0x8000000L, active1, (ulong)0L);
      case ((char) 101):
         if ((active0 & 0x80000L) != (ulong)0L)
            return jjStartNfaWithStates_0(8, 19, 13);
         else if ((active0 & 0x2000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(8, 25, 13);
         else if ((active1 & 0x4000L) != (ulong)0L)
            return jjStartNfaWithStates_0(8, 78, 13);
         else if ((active1 & 0x800000L) != (ulong)0L)
            return jjStartNfaWithStates_0(8, 87, 13);
         break;
      case ((char) 110):
         if ((active1 & 0x8000L) != (ulong)0L)
            return jjStartNfaWithStates_0(8, 79, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, (ulong)active0, (ulong)active1);
}
private int jjMoveStringLiteralDfa9_0(ulong old0, ulong active0, ulong old1, ulong active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == (ulong)0L)
      return jjStartNfa_0(7, (ulong)old0, (ulong)old1); 
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(8, (ulong)active0, (ulong)0L);
      return 9;
   }
   switch(curChar)
   {
      case ((char) 108):
         return jjMoveStringLiteralDfa10_0(active0, (ulong)0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, (ulong)active0, (ulong)0L);
}
private int jjMoveStringLiteralDfa10_0(ulong old0, ulong active0)
{
   if (((active0 &= old0)) == (ulong)0L)
      return jjStartNfa_0(8, (ulong)old0, (ulong)0L);
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      jjStopStringLiteralDfa_0(9, (ulong)active0, (ulong)0L);
      return 10;
   }
   switch(curChar)
   {
      case ((char) 101):
         if ((active0 & 0x8000000L) != (ulong)0L)
            return jjStartNfaWithStates_0(10, 27, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, (ulong)active0, (ulong)0L);
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static ulong[] jjbitVec0 = {
   (ulong)0xfffffffffffffffeL, (ulong)0xffffffffffffffffL, (ulong)0xffffffffffffffffL, (ulong)0xffffffffffffffffL
};
static ulong[] jjbitVec1 = {
   (ulong)0xffffffffffffffffL, (ulong)0xffffffffffffffffL, (ulong)0xffffffffffffffffL, (ulong)0xffffffffffffffffL
};
static ulong[] jjbitVec2 = {
   (ulong)0x0L, (ulong)0x0L, (ulong)0xffffffffffffffffL, (ulong)0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 85;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         ulong l = ((ulong)1L) << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(0, 5);
                  else if (curChar == 34)
                     jjCheckNAddStates(6, 11);
                  else if (curChar == 39)
                     jjAddStates(12, 13);
                  else if (curChar == 46)
                     jjCheckNAdd(15);
                  else if (curChar == 35)
                     jjCheckNAddTwoStates(1, 2);
                  if ((0x3fe000000000000L & l) != (ulong)0L)
                  {
                     if (kind > 95)
                        kind = 95;
                     jjCheckNAddStates(14, 16);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 95)
                        kind = 95;
                     jjCheckNAdd(39);
                  }
                  if (curChar == 48)
                     jjAddStates(17, 18);
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(19, 22);
                  else if ((0x100000200L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 1:
                  if ((0x100000200L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(19, 22);
                  break;
               case 3:
                  if ((0x100000200L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 34)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0xfffffffbffffffffL & l) != (ulong)0L)
                     jjCheckNAddTwoStates(5, 6);
                  break;
               case 6:
                  if (curChar == 34)
                     jjCheckNAddStates(23, 25);
                  break;
               case 7:
                  if (curChar == 10 && kind > 7)
                     kind = 7;
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(26, 29);
                  break;
               case 9:
                  if ((0x100000200L & l) != (ulong)0L)
                     jjCheckNAddStates(30, 32);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(10, 7);
                  break;
               case 11:
                  if ((0x100000200L & l) != (ulong)0L)
                     jjCheckNAddStates(33, 37);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 93)
                     kind = 93;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 14:
                  if (curChar == 46)
                     jjCheckNAdd(15);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  jjCheckNAddStates(38, 40);
                  break;
               case 17:
                  if ((0x280000000000L & l) != (ulong)0L)
                     jjCheckNAdd(18);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  jjCheckNAddTwoStates(18, 19);
                  break;
               case 20:
                  if (curChar == 39)
                     jjAddStates(12, 13);
                  break;
               case 21:
                  if ((0xffffff7fffffdbffL & l) != (ulong)0L)
                     jjCheckNAdd(22);
                  break;
               case 22:
                  if (curChar == 39 && kind > 99)
                     kind = 99;
                  break;
               case 24:
                  if ((0x8000008400000000L & l) != (ulong)0L)
                     jjCheckNAdd(22);
                  break;
               case 25:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(26, 22);
                  break;
               case 26:
                  if ((0xff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(26, 22);
                  break;
               case 27:
                  if ((0x3fe000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(28, 22);
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(28, 22);
                  break;
               case 29:
                  if (curChar == 48)
                     jjAddStates(41, 42);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(31, 22);
                  break;
               case 33:
                  if (curChar == 48)
                     jjAddStates(17, 18);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 96)
                     kind = 96;
                  jjAddStates(43, 44);
                  break;
               case 38:
                  if (curChar != 48)
                     break;
                  if (kind > 95)
                     kind = 95;
                  jjCheckNAdd(39);
                  break;
               case 39:
                  if ((0xff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 41:
                  if ((0x3fe000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 95)
                     kind = 95;
                  jjCheckNAddStates(14, 16);
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 95)
                     kind = 95;
                  jjCheckNAddTwoStates(42, 43);
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 103)
                     kind = 103;
                  jjCheckNAdd(44);
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(0, 5);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(46, 47);
                  break;
               case 47:
                  if (curChar != 46)
                     break;
                  if (kind > 97)
                     kind = 97;
                  jjCheckNAddStates(45, 47);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  jjCheckNAddStates(45, 47);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(49, 14);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddTwoStates(50, 51);
                  break;
               case 52:
                  if ((0x280000000000L & l) != (ulong)0L)
                     jjCheckNAdd(53);
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) == (ulong)0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  jjCheckNAddTwoStates(53, 54);
                  break;
               case 55:
                  if (curChar == 34)
                     jjCheckNAddStates(6, 11);
                  break;
               case 56:
                  if ((0xfffffffbffffdbffL & l) != (ulong)0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 58:
                  if ((0x8000008400000000L & l) != (ulong)0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 59:
                  if (curChar == 34 && kind > 100)
                     kind = 100;
                  break;
               case 60:
                  if (curChar == 48)
                     jjCheckNAddStates(51, 54);
                  break;
               case 61:
                  if ((0xff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(51, 54);
                  break;
               case 62:
                  if ((0x3fe000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(55, 58);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(55, 58);
                  break;
               case 64:
                  if (curChar == 48)
                     jjAddStates(59, 60);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(61, 64);
                  break;
               case 69:
                  if ((0xfffffffbffffdbffL & l) != (ulong)0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 71:
                  if ((0x8000008400000000L & l) != (ulong)0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 72:
                  if (curChar == 34 && kind > 101)
                     kind = 101;
                  break;
               case 73:
                  if (curChar == 48)
                     jjCheckNAddStates(68, 71);
                  break;
               case 74:
                  if ((0xff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(68, 71);
                  break;
               case 75:
                  if ((0x3fe000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(72, 75);
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(72, 75);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(76, 79);
                  break;
               case 79:
                  if (curChar == 48)
                     jjAddStates(80, 81);
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != (ulong)0L)
                     jjCheckNAddStates(82, 85);
                  break;
               case 83:
                  if ((0xfffffffbffffdbffL & l) != (ulong)0L)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 84:
                  if (curChar == 34 && kind > 102)
                     kind = 102;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         ulong l = ((ulong)1L) << (curChar & 0x3F);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 13:
                  if ((0x7fffffe87fffffeL & l) == (ulong)0L)
                     break;
                  if (kind > 93)
                     kind = 93;
                  jjCheckNAdd(13);
                  break;
               case 5:
                  jjAddStates(86, 87);
                  break;
               case 16:
                  if ((0x2000000020L & l) != (ulong)0L)
                     jjAddStates(88, 89);
                  break;
               case 19:
                  if ((0x104000001040L & l) != (ulong)0L && kind > 97)
                     kind = 97;
                  break;
               case 21:
                  if ((0xffffffffefffffffL & l) != (ulong)0L)
                     jjCheckNAdd(22);
                  break;
               case 23:
                  if (curChar == 92)
                     jjAddStates(90, 93);
                  break;
               case 24:
                  if ((0x54404610000000L & l) != (ulong)0L)
                     jjCheckNAdd(22);
                  break;
               case 30:
                  if (curChar == 120)
                     jjCheckNAdd(31);
                  break;
               case 31:
                  if ((0x7e0000007eL & l) != (ulong)0L)
                     jjCheckNAddTwoStates(31, 22);
                  break;
               case 32:
                  if (curChar == 88)
                     jjCheckNAdd(31);
                  break;
               case 34:
                  if (curChar == 120)
                     jjCheckNAdd(35);
                  break;
               case 35:
                  if ((0x7e0000007eL & l) == (ulong)0L)
                     break;
                  if (kind > 96)
                     kind = 96;
                  jjCheckNAddTwoStates(35, 36);
                  break;
               case 36:
                  if ((0x20100000201000L & l) != (ulong)0L && kind > 96)
                     kind = 96;
                  break;
               case 37:
                  if (curChar == 88)
                     jjCheckNAdd(35);
                  break;
               case 40:
                  if ((0x20100000201000L & l) != (ulong)0L && kind > 94)
                     kind = 94;
                  break;
               case 43:
                  if ((0x20100000201000L & l) != (ulong)0L && kind > 95)
                     kind = 95;
                  break;
               case 51:
                  if ((0x2000000020L & l) != (ulong)0L)
                     jjAddStates(94, 95);
                  break;
               case 54:
                  if ((0x104000001040L & l) != (ulong)0L && kind > 98)
                     kind = 98;
                  break;
               case 56:
                  if ((0xffffffffefffffffL & l) != (ulong)0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 57:
                  if (curChar == 92)
                     jjAddStates(96, 99);
                  break;
               case 58:
                  if ((0x54404610000000L & l) != (ulong)0L)
                     jjCheckNAddStates(48, 50);
                  break;
               case 65:
                  if (curChar == 120)
                     jjCheckNAdd(66);
                  break;
               case 66:
                  if ((0x7e0000007eL & l) != (ulong)0L)
                     jjCheckNAddStates(61, 64);
                  break;
               case 67:
                  if (curChar == 88)
                     jjCheckNAdd(66);
                  break;
               case 68:
                  if (curChar == 76)
                     jjCheckNAddStates(65, 67);
                  break;
               case 69:
                  if ((0xffffffffefffffffL & l) != (ulong)0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 70:
                  if (curChar == 92)
                     jjAddStates(100, 104);
                  break;
               case 71:
                  if ((0x54404610000000L & l) != (ulong)0L)
                     jjCheckNAddStates(65, 67);
                  break;
               case 77:
                  if (curChar == 117)
                     jjCheckNAdd(78);
                  break;
               case 78:
                  if ((0x7e0000007eL & l) != (ulong)0L)
                     jjCheckNAddStates(76, 79);
                  break;
               case 80:
                  if (curChar == 120)
                     jjCheckNAdd(81);
                  break;
               case 81:
                  if ((0x7e0000007eL & l) != (ulong)0L)
                     jjCheckNAddStates(82, 85);
                  break;
               case 82:
                  if (curChar == 88)
                     jjCheckNAdd(81);
                  break;
               case 83:
                  jjAddStates(105, 106);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         ulong l1 = ((ulong)1L) << (hiByte & 0x3F);
         int i2 = (curChar & 0xff) >> 6;
         ulong l2 = ((ulong)1L) << (curChar & 0x3F);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(86, 87);
                  break;
               case 21:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 56:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(48, 50);
                  break;
               case 69:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(65, 67);
                  break;
               case 83:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(105, 106);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 85 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(System.IO.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case ((char) 10):
         return jjStopAtPos(0, 8);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case ((char) 42):
         return jjMoveStringLiteralDfa1_2((ulong)0x400L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_2(ulong active0)
{
   try { curChar = input_stream.readChar(); }
   catch(System.IO.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case ((char) 47):
         if ((active0 & 0x400L) != (ulong)0L)
            return jjStopAtPos(1, 10);
         break;
      default :
         return 2;
   }
   return 2;
}
static int[] jjnextStates = {
   46, 47, 49, 14, 50, 51, 56, 57, 59, 68, 83, 84, 21, 23, 42, 43, 
   44, 34, 37, 2, 3, 4, 7, 7, 8, 11, 9, 10, 7, 8, 9, 10, 
   7, 9, 10, 7, 8, 11, 15, 16, 19, 30, 32, 35, 36, 48, 16, 19, 
   56, 57, 59, 56, 57, 61, 59, 56, 57, 63, 59, 65, 67, 56, 57, 66, 
   59, 69, 70, 72, 69, 70, 74, 72, 69, 70, 76, 72, 69, 70, 78, 72, 
   80, 82, 69, 70, 81, 72, 5, 6, 17, 18, 24, 25, 27, 29, 52, 53, 
   58, 60, 62, 64, 71, 73, 75, 77, 79, 83, 84, 
};
private static bool jjCanMove_0(int hiByte, int i1, int i2, ulong l1, ulong l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != (ulong)0L);
      default : 
         if ((jjbitVec0[i1] & l1) != (ulong)0L)
            if ((jjbitVec1[i2] & l2) == (ulong)0L)
               return false;
            else
            return true;
         return false;
   }
}
public static String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, 
"\x23\x70\x72\x61\x67\x6d\x61", "\x49\x44", "\x70\x72\x65\x66\x69\x78", "\x3b", "\x6d\x6f\x64\x75\x6c\x65", 
"\x7b", "\x7d", "\x69\x6e\x74\x65\x72\x66\x61\x63\x65", 
"\x61\x62\x73\x74\x72\x61\x63\x74", "\x6c\x6f\x63\x61\x6c", "\x3a", "\x2c", "\x3a\x3a", 
"\x76\x61\x6c\x75\x65\x74\x79\x70\x65", "\x63\x75\x73\x74\x6f\x6d", "\x74\x72\x75\x6e\x63\x61\x74\x61\x62\x6c\x65", 
"\x73\x75\x70\x70\x6f\x72\x74\x73", "\x70\x75\x62\x6c\x69\x63", "\x70\x72\x69\x76\x61\x74\x65", 
"\x66\x61\x63\x74\x6f\x72\x79", "\x28", "\x29", "\x69\x6e", "\x63\x6f\x6e\x73\x74", "\x4e\x61\x4e", "\x3d", 
"\x7c", "\x5e", "\x26", "\x3e\x3e", "\x3c\x3c", "\x2b", "\x2d", "\x2a", "\x2f", 
"\x25", "\x7e", "\x54\x52\x55\x45", "\x46\x41\x4c\x53\x45", 
"\x74\x79\x70\x65\x64\x65\x66", "\x6e\x61\x74\x69\x76\x65", "\x66\x6c\x6f\x61\x74", 
"\x64\x6f\x75\x62\x6c\x65", "\x6c\x6f\x6e\x67", "\x73\x68\x6f\x72\x74", 
"\x75\x6e\x73\x69\x67\x6e\x65\x64", "\x63\x68\x61\x72", "\x77\x63\x68\x61\x72", "\x62\x6f\x6f\x6c\x65\x61\x6e", 
"\x6f\x63\x74\x65\x74", "\x61\x6e\x79", "\x4f\x62\x6a\x65\x63\x74", "\x73\x74\x72\x75\x63\x74", 
"\x75\x6e\x69\x6f\x6e", "\x73\x77\x69\x74\x63\x68", "\x63\x61\x73\x65", 
"\x64\x65\x66\x61\x75\x6c\x74", "\x65\x6e\x75\x6d", "\x73\x65\x71\x75\x65\x6e\x63\x65", "\x3c", "\x3e", 
"\x73\x74\x72\x69\x6e\x67", "\x77\x73\x74\x72\x69\x6e\x67", "\x5b", "\x5d", 
"\x72\x65\x61\x64\x6f\x6e\x6c\x79", "\x61\x74\x74\x72\x69\x62\x75\x74\x65", 
"\x65\x78\x63\x65\x70\x74\x69\x6f\x6e", "\x6f\x6e\x65\x77\x61\x79", "\x76\x6f\x69\x64", "\x6f\x75\x74", 
"\x69\x6e\x6f\x75\x74", "\x72\x61\x69\x73\x65\x73", "\x63\x6f\x6e\x74\x65\x78\x74", 
"\x66\x69\x78\x65\x64", "\x56\x61\x6c\x75\x65\x42\x61\x73\x65", "\x4c", 
"\x49\x6e\x66\x69\x6e\x69\x74\x79", "\x2e", "\x64", "\x44", null, null, null, null, null, null, null, null, null, 
null, null, };
public static String[] lexStateNames = {
   "DEFAULT", 
   "IN_LINE_COMMENT", 
   "IN_COMMENT", 
};
public static int[] jjnewLexState = {
   -1, -1, -1, -1, -1, 1, 2, -1, 0, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, 
};
static ulong[] jjtoToken = {
   0xfffffffffffff001L, 0xffffffffffL, 
};
static long[] jjtoSkip = {
   0x5feL, 0x0L, 
};
static long[] jjtoMore = {
   0xa00L, 0x0L, 
};
protected JavaCharStream input_stream;
private uint[] jjrounds = new uint[85];
private int[] jjstateSet = new int[170];
protected char curChar;
public IDLParserTokenManager(JavaCharStream stream)
{
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public IDLParserTokenManager(JavaCharStream stream, int lexState) : this(stream)
{
   SwitchTo(lexState);
}
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 85; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
uint jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(System.IO.IOException)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   catch(System.ObjectDisposedException)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (System.IO.IOException e1) { goto EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 9)
         {
            jjmatchedKind = 9;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 11)
         {
            jjmatchedKind = 11;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & ((ulong)(1L << (jjmatchedKind & 0x3F)))) != (ulong)0L)
        {
           matchedToken = jjFillToken();
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 0x3F))) != 0L)
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           goto EOFLoop;
        }
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (System.IO.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     bool EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (System.IO.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

}
