/* Generated By:JJTree&JavaCC: Do not edit this line. IDLParserConstants.cs */
using System;

public class IDLParserConstants {

  int EOF = 0;
  public const int PRAGMA = 86;
  public const int PRAGMAID = 87;
  public const int PRAGMAPREFIX = 88;
  public const int ID = 89;
  public const int OCTALINT = 90;
  public const int DECIMALINT = 91;
  public const int HEXADECIMALINT = 92;
  public const int FLOATONE = 93;
  public const int FLOATTWO = 94;
  public const int CHARACTER = 95;
  public const int WIDECHARACTER = 96;
  public const int STRING = 97;
  public const int WIDESTRING = 98;
  public const int REPIDVAL_STRING = 99;
  public const int FIXED = 100;

  public const int DEFAULT = 0;
  public const int PRAGMA_DIRECTIVE = 1;
  public const int IN_LINE_COMMENT = 2;
  public const int IN_COMMENT = 3;

  public static String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "\";\"",
    "\"module\"",
    "\"{\"",
    "\"}\"",
    "\"interface\"",
    "\"abstract\"",
    "\"local\"",
    "\":\"",
    "\",\"",
    "\"::\"",
    "\"valuetype\"",
    "\"custom\"",
    "\"truncatable\"",
    "\"supports\"",
    "\"public\"",
    "\"private\"",
    "\"factory\"",
    "\"(\"",
    "\")\"",
    "\"in\"",
    "\"const\"",
    "\"NaN\"",
    "\"=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"typedef\"",
    "\"native\"",
    "\"float\"",
    "\"double\"",
    "\"long\"",
    "\"short\"",
    "\"unsigned\"",
    "\"char\"",
    "\"wchar\"",
    "\"boolean\"",
    "\"octet\"",
    "\"any\"",
    "\"Object\"",
    "\"struct\"",
    "\"union\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"enum\"",
    "\"sequence\"",
    "\"<\"",
    "\">\"",
    "\"string\"",
    "\"wstring\"",
    "\"[\"",
    "\"]\"",
    "\"readonly\"",
    "\"attribute\"",
    "\"exception\"",
    "\"oneway\"",
    "\"void\"",
    "\"out\"",
    "\"inout\"",
    "\"raises\"",
    "\"context\"",
    "\"fixed\"",
    "\"ValueBase\"",
    "\"Infinity\"",
    "\"#pragma\"",
    "\"ID\"",
    "\"prefix\"",
    "<ID>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<WIDECHARACTER>",
    "<STRING>",
    "<WIDESTRING>",
    "<REPIDVAL_STRING>",
    "<FIXED>",
  };

}
