/* Generated By:JJTree&JavaCC: Do not edit this line. IDLParserConstants.java */
package parser;

public interface IDLParserConstants {

  int EOF = 0;
  int ID = 90;
  int OCTALINT = 91;
  int DECIMALINT = 92;
  int HEXADECIMALINT = 93;
  int FLOATONE = 94;
  int FLOATTWO = 95;
  int CHARACTER = 96;
  int STRING = 97;
  int FIXED = 98;

  int DEFAULT = 0;
  int IN_LINE_COMMENT = 1;
  int IN_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "\"#pragma\"",
    "\"ID\"",
    "\"prefix\"",
    "\";\"",
    "\"module\"",
    "\"{\"",
    "\"}\"",
    "\"abstract\"",
    "\"interface\"",
    "\":\"",
    "\",\"",
    "\"::\"",
    "\"valuetype\"",
    "\"custom\"",
    "\"truncatable\"",
    "\"supports\"",
    "\"public\"",
    "\"private\"",
    "\"factory\"",
    "\"(\"",
    "\")\"",
    "\"in\"",
    "\"const\"",
    "\"=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"typedef\"",
    "\"native\"",
    "\"float\"",
    "\"double\"",
    "\"long\"",
    "\"short\"",
    "\"unsigned\"",
    "\"char\"",
    "\"wchar\"",
    "\"boolean\"",
    "\"octet\"",
    "\"any\"",
    "\"Object\"",
    "\"struct\"",
    "\"union\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"enum\"",
    "\"sequence\"",
    "\"<\"",
    "\">\"",
    "\"string\"",
    "\"wstring\"",
    "\"[\"",
    "\"]\"",
    "\"readonly\"",
    "\"attribute\"",
    "\"exception\"",
    "\"oneway\"",
    "\"void\"",
    "\"out\"",
    "\"inout\"",
    "\"raises\"",
    "\"context\"",
    "\"fixed\"",
    "\"ValueBase\"",
    "\"L\"",
    "\".\"",
    "\"d\"",
    "\"D\"",
    "<ID>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "<FIXED>",
  };

}
