module Ch {
module Elca {
module Iiop {
module IntegrationTests {


    enum TestEnumForU2 {
        A1, B1, C1
    };


    union TestUnionE2 switch(TestEnumForU2) {
        case A1: short valE0;
        case B1:
        case C1: TestEnumForU2 valE1;
    };


};
};
};
};