include ../../../../MakeVars.mono
NUNIT=${NUNITV2_HOME}/$(NUNIT_BIN_SUBDIR)nunit.framework.dll
IIOPCHANNEL = ../../../../IIOPChannel/bin/IIOPChannel.dll
bin = bin/
binTmp      = binTmp/

build: build-client

build-client: $(bin)ClientTest.dll

compile-idl: IDL/Ch/Elca/Iiop/IntegrationTests/TestService.idl


IDL/Ch/Elca/Iiop/IntegrationTests/TestService.idl: ../TestServer/IDL/Ch/Elca/Iiop/IntegrationTests/TestService.idl
	[ -d IDL ] || mkdir IDL
	cp -f ../../../../IDLToCLSCompiler/IDL/*.idl IDL
	cp -r ../TestServer/IDL/* IDL


$(binTmp)client.dll: IDL/Ch/Elca/Iiop/IntegrationTests/TestService.idl IDL/Ch/Elca/Iiop/IntegrationTests/TestExceptionService.idl IDL/Ch/Elca/Iiop/IntegrationTests/ISimpleTestInterface.idl IDL/Ch/Elca/Iiop/IntegrationTests/TestBoxedValueTypeService.idl
	cd IDL; mono ../../../../../IDLToCLSCompiler/IDLCompiler/bin/IDLToCLSCompiler.exe -o ../$(binTmp) -snk ../../../../../Key.snk client Ch/Elca/Iiop/IntegrationTests/TestService.idl Ch/Elca/Iiop/IntegrationTests/TestExceptionService.idl Ch/Elca/Iiop/IntegrationTests/ISimpleTestInterface.idl Ch/Elca/Iiop/IntegrationTests/TestBoxedValueTypeService.idl

$(bin)ClientTest.dll: $(binTmp)client.dll *.cs
	[ -d $(bin) ] || mkdir $(bin)
	$(CSC) $(CSFLAGS) /t:library /r:$(NUNIT) /r:$(IIOPCHANNEL) /r:$(binTmp)client.dll /out:$(bin)ClientTest.dll TestClient.cs ValueTypeImpls.cs

start-client: install-gac
	@echo "Basic GAC IntegrationTest"
	mono ${NUNITV2_HOME}/$(NUNIT_BIN_SUBDIR)nunit-console.exe bin/ClientTest.dll
	$(MAKE) Makefile -C uninstall-gac

install-gac:
	gacutil /i $(IIOPCHANNEL)
	gacutil /i $(binTmp)client.dll

uninstall-gac:
	gacutil /u client
	gacutil /u IIOPChannel
	

clean: 
	rm -rf IDL
	rm -rf bin
	rm -rf $(binTmp)


