

union TestUnion switch (long) {
    case 0: short val0;
    case 1: 
    case 2: long val1;
    default: boolean val2;
};

enum TestEnumForU {
    A, B, C
};

union TestUnionE switch(TestEnumForU) {
    case A: short valE0;
    case B:
    case C: TestEnumForU valE1;
};

typedef sequence<wstring> wstringSeq;

interface TestService {
    TestUnion EchoTestUnion(in TestUnion arg);
    TestUnionE EchoTestUnionE(in TestUnionE arg);   
    any EchoAny(in any arg);
    any RetrieveUnknownUnion();
    // test for forum bug report: idl wstring sequences
    wstringSeq RetrieveWstringSeq(in wstring val, in long nrOfElems);
    wstringSeq EchoWstringSeq(in wstringSeq arg);
}; 




