include ..\..\MakeVars

build:
	cd Server
	$(MAKE) build
	cd ..
        cd Client
        $(MAKE) build
        cd ..

clean:
	cd Server
	$(MAKE) clean
	cd ..
        cd Client
        $(MAKE) clean
        cd ..

start-server:
	cd Server
	$(MAKE) start-server
 	cd ..
 
stop-server:
 	cd Server
 	$(MAKE) stop-server
 	cd ..
