include ..\..\..\..\MakeVars

build:
	cd java
	$(MAKE) build
	cd ..
        cd net
        $(MAKE) build
        cd ..

clean:
	cd java
	$(MAKE) clean
	cd ..
        cd net
	$(MAKE) clean
        cd ..
