include ../../MakeVars.mono

build:
	$(MAKE) -C InvocationScenarios build -f Makefile.mono

test:
	$(MAKE) -C InvocationScenarios test -f Makefile.mono

clean:
	$(MAKE) -C InvocationScenarios clean -f Makefile.mono
