build:
	cd server
	$(MAKE) build
	cd ..
        cd directclient
        $(MAKE) build
        cd ..
        cd idlclient
        $(MAKE) build
        cd ..


clean:
	cd server
	$(MAKE) clean
	cd ..
        cd directClient
        $(MAKE) clean
        cd ..
        cd idlClient
        $(MAKE) clean
        cd ..
