/* Generated By:JJTree: Do not edit this line. ASTcase_label.cs */

using System;

namespace parser {

public class ASTcase_label : SimpleNode {
  public ASTcase_label(int id) : base(id) {
  }

  public ASTcase_label(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

