/* Generated By:JJTree: Do not edit this line. ASTconst_exp.cs */

using System;

namespace parser {

public class ASTconst_exp : SimpleNode {
  public ASTconst_exp(int id) : base(id) {
  }

  public ASTconst_exp(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

