/* Generated By:JJTree: Do not edit this line. ASTraises_expr.cs */

using System;

namespace parser {

public class ASTraises_expr : SimpleNode {
  public ASTraises_expr(int id) : base(id) {
  }

  public ASTraises_expr(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}


}

