/* Generated By:JJTree: Do not edit this line. IDLParserTreeConstants.cs */

using System;

namespace parser {

public class IDLParserTreeConstants
{
  public const int JJTVOID = 0;
  public const int JJTSPECIFICATION = 1;
  public const int JJTDEFINITION = 2;
  public const int JJTMODULE = 3;
  public const int JJTINTERFACEX = 4;
  public const int JJTINTERFACE_DCL = 5;
  public const int JJTFORWARD_DCL = 6;
  public const int JJTINTERFACE_HEADER = 7;
  public const int JJTINTERFACE_BODY = 8;
  public const int JJTEXPORT = 9;
  public const int JJTINTERFACE_INHERITANCE_SPEC = 10;
  public const int JJTINTERFACE_NAME = 11;
  public const int JJTSCOPED_NAME = 12;
  public const int JJTVALUE = 13;
  public const int JJTVALUE_FORWARD_DECL = 14;
  public const int JJTVALUE_BOX_DECL = 15;
  public const int JJTVALUE_ABS_DECL = 16;
  public const int JJTVALUE_DECL = 17;
  public const int JJTVALUE_HEADER = 18;
  public const int JJTVALUE_BASE_INHERITANCE_SPEC = 19;
  public const int JJTVALUE_SUPPORT_INHERITANCE_SPEC = 20;
  public const int JJTVALUE_NAME = 21;
  public const int JJTVALUE_ELEMENT = 22;
  public const int JJTSTATE_MEMBER = 23;
  public const int JJTINIT_DECL = 24;
  public const int JJTINIT_PARAM_DELCS = 25;
  public const int JJTINIT_PARAM_DECL = 26;
  public const int JJTINIT_PARAM_ATTRIBUTE = 27;
  public const int JJTCONST_DCL = 28;
  public const int JJTCONST_TYPE = 29;
  public const int JJTCONST_EXP = 30;
  public const int JJTOR_EXPR = 31;
  public const int JJTXOR_EXPR = 32;
  public const int JJTAND_EXPR = 33;
  public const int JJTSHIFT_EXPR = 34;
  public const int JJTADD_EXPR = 35;
  public const int JJTMULT_EXPR = 36;
  public const int JJTUNARY_EXPR = 37;
  public const int JJTPRIMARY_EXPR = 38;
  public const int JJTLITERAL = 39;
  public const int JJTPOSITIVE_INT_CONST = 40;
  public const int JJTTYPE_DCL = 41;
  public const int JJTTYPE_DECLARATOR = 42;
  public const int JJTTYPE_SPEC = 43;
  public const int JJTSIMPLE_TYPE_SPEC = 44;
  public const int JJTBASE_TYPE_SPEC = 45;
  public const int JJTTEMPLATE_TYPE_SPEC = 46;
  public const int JJTCONSTR_TYPE_SPEC = 47;
  public const int JJTDECLARATORS = 48;
  public const int JJTDECLARATOR = 49;
  public const int JJTSIMPLE_DECLARATOR = 50;
  public const int JJTCOMPLEX_DECLARATOR = 51;
  public const int JJTFLOATING_PT_TYPE = 52;
  public const int JJTFLOATING_PT_TYPE_FLOAT = 53;
  public const int JJTFLOATING_PT_TYPE_DOUBLE = 54;
  public const int JJTFLOATING_PT_TYPE_LONGDOUBLE = 55;
  public const int JJTINTEGER_TYPE = 56;
  public const int JJTSIGNED_INT = 57;
  public const int JJTSIGNED_SHORT_INT = 58;
  public const int JJTSIGNED_LONG_INT = 59;
  public const int JJTSIGNED_LONGLONG_INT = 60;
  public const int JJTUNSIGNED_INT = 61;
  public const int JJTUNSIGNED_SHORT_INT = 62;
  public const int JJTUNSIGNED_LONG_INT = 63;
  public const int JJTUNSIGNED_LONGLONG_INT = 64;
  public const int JJTCHAR_TYPE = 65;
  public const int JJTWIDE_CHAR_TYPE = 66;
  public const int JJTBOOLEAN_TYPE = 67;
  public const int JJTOCTET_TYPE = 68;
  public const int JJTANY_TYPE = 69;
  public const int JJTOBJECT_TYPE = 70;
  public const int JJTSTRUCT_TYPE = 71;
  public const int JJTMEMBER_LIST = 72;
  public const int JJTMEMBER = 73;
  public const int JJTUNION_TYPE = 74;
  public const int JJTSWITCH_TYPE_SPEC = 75;
  public const int JJTSWITCH_BODY = 76;
  public const int JJTCASEX = 77;
  public const int JJTCASE_LABEL = 78;
  public const int JJTELEMENT_SPEC = 79;
  public const int JJTENUM_TYPE = 80;
  public const int JJTENUMERATOR = 81;
  public const int JJTSEQUENCE_TYPE = 82;
  public const int JJTSTRING_TYPE = 83;
  public const int JJTWIDE_STRING_TYPE = 84;
  public const int JJTARRAY_DECLARATOR = 85;
  public const int JJTFIXED_ARRAY_SIZE = 86;
  public const int JJTATTR_DCL = 87;
  public const int JJTEXCEPT_DCL = 88;
  public const int JJTOP_DCL = 89;
  public const int JJTOP_TYPE_SPEC = 90;
  public const int JJTPARAMETER_DCLS = 91;
  public const int JJTPARAM_DCL = 92;
  public const int JJTPARAM_ATTRIBUTE = 93;
  public const int JJTRAISES_EXPR = 94;
  public const int JJTCONTEXT_EXPR = 95;
  public const int JJTPARAM_TYPE_SPEC = 96;
  public const int JJTFIXED_PT_TYPE = 97;
  public const int JJTFIXED_PT_CONST_TYPE = 98;
  public const int JJTVALUE_BASE_TYPE = 99;


  public static String[] jjtNodeName = {
    "void",
    "specification",
    "definition",
    "module",
    "interfacex",
    "interface_dcl",
    "forward_dcl",
    "interface_header",
    "interface_body",
    "export",
    "interface_inheritance_spec",
    "interface_name",
    "scoped_name",
    "value",
    "value_forward_decl",
    "value_box_decl",
    "value_abs_decl",
    "value_decl",
    "value_header",
    "value_base_inheritance_spec",
    "value_support_inheritance_spec",
    "value_name",
    "value_element",
    "state_member",
    "init_decl",
    "init_param_delcs",
    "init_param_decl",
    "init_param_attribute",
    "const_dcl",
    "const_type",
    "const_exp",
    "or_expr",
    "xor_expr",
    "and_expr",
    "shift_expr",
    "add_expr",
    "mult_expr",
    "unary_expr",
    "primary_expr",
    "literal",
    "positive_int_const",
    "type_dcl",
    "type_declarator",
    "type_spec",
    "simple_type_spec",
    "base_type_spec",
    "template_type_spec",
    "constr_type_spec",
    "declarators",
    "declarator",
    "simple_declarator",
    "complex_declarator",
    "floating_pt_type",
    "floating_pt_type_float",
    "floating_pt_type_double",
    "floating_pt_type_longdouble",
    "integer_type",
    "signed_int",
    "signed_short_int",
    "signed_long_int",
    "signed_longlong_int",
    "unsigned_int",
    "unsigned_short_int",
    "unsigned_long_int",
    "unsigned_longlong_int",
    "char_type",
    "wide_char_type",
    "boolean_type",
    "octet_type",
    "any_type",
    "object_type",
    "struct_type",
    "member_list",
    "member",
    "union_type",
    "switch_type_spec",
    "switch_body",
    "casex",
    "case_label",
    "element_spec",
    "enum_type",
    "enumerator",
    "sequence_type",
    "string_type",
    "wide_string_type",
    "array_declarator",
    "fixed_array_size",
    "attr_dcl",
    "except_dcl",
    "op_dcl",
    "op_type_spec",
    "parameter_dcls",
    "param_dcl",
    "param_attribute",
    "raises_expr",
    "context_expr",
    "param_type_spec",
    "fixed_pt_type",
    "fixed_pt_const_type",
    "value_base_type",
  };
}


}

