/* Generated By:JJTree&JavaCC: Do not edit this line. IDLParserConstants.cs */
using System;

public class IDLParserConstants {

  int EOF = 0;
  public const int ID = 91;
  public const int OCTALINT = 92;
  public const int DECIMALINT = 93;
  public const int HEXADECIMALINT = 94;
  public const int FLOATONE = 95;
  public const int FLOATTWO = 96;
  public const int CHARACTER = 97;
  public const int STRING = 98;
  public const int FIXED = 99;

  public const int DEFAULT = 0;
  public const int IN_LINE_COMMENT = 1;
  public const int IN_COMMENT = 2;

  public static String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"\\n\"",
    "<token of kind 9>",
    "\"*/\"",
    "<token of kind 11>",
    "\"#pragma\"",
    "\"ID\"",
    "\"prefix\"",
    "\";\"",
    "\"module\"",
    "\"{\"",
    "\"}\"",
    "\"interface\"",
    "\"abstract\"",
    "\"local\"",
    "\":\"",
    "\",\"",
    "\"::\"",
    "\"valuetype\"",
    "\"custom\"",
    "\"truncatable\"",
    "\"supports\"",
    "\"public\"",
    "\"private\"",
    "\"factory\"",
    "\"(\"",
    "\")\"",
    "\"in\"",
    "\"const\"",
    "\"=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"typedef\"",
    "\"native\"",
    "\"float\"",
    "\"double\"",
    "\"long\"",
    "\"short\"",
    "\"unsigned\"",
    "\"char\"",
    "\"wchar\"",
    "\"boolean\"",
    "\"octet\"",
    "\"any\"",
    "\"Object\"",
    "\"struct\"",
    "\"union\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"enum\"",
    "\"sequence\"",
    "\"<\"",
    "\">\"",
    "\"string\"",
    "\"wstring\"",
    "\"[\"",
    "\"]\"",
    "\"readonly\"",
    "\"attribute\"",
    "\"exception\"",
    "\"oneway\"",
    "\"void\"",
    "\"out\"",
    "\"inout\"",
    "\"raises\"",
    "\"context\"",
    "\"fixed\"",
    "\"ValueBase\"",
    "\"L\"",
    "\".\"",
    "\"d\"",
    "\"D\"",
    "<ID>",
    "<OCTALINT>",
    "<DECIMALINT>",
    "<HEXADECIMALINT>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "<FIXED>",
  };

}
